# Generated by Django 4.1 on 2022-08-14 15:25

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('geom', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.gis.db.models.fields.PointField(srid=4326), size=None)),
            ],
            options={
                'verbose_name_plural': 'Geometry',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('pk_track', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('noiselevel', models.DecimalField(blank=True, decimal_places=2, max_digits=20)),
                ('timelength', models.DecimalField(blank=True, decimal_places=1, max_digits=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('time_epoch', models.IntegerField(blank=True)),
                ('pleasantness', models.IntegerField(blank=True)),
                ('track_uuid', models.CharField(blank=True, max_length=1000)),
                ('time_ISO8601', models.DateTimeField(blank=True)),
                ('geom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.geometry')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
