# Generated by Django 4.0 on 2023-02-19 22:55

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(help_text="use'[algo]$[salt]$[hexdigest]'", max_length=128, verbose_name='password')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['created_on'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('Type', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Geometry',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('pk_track', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('noiselevel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timelength', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('time_epoch', models.CharField(blank=True, max_length=200, null=True)),
                ('pleasantness', models.IntegerField(blank=True, null=True)),
                ('track_uuid', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_ISO8601', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='UserUploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('noiselevel', models.CharField(blank=True, max_length=200, null=True)),
                ('timelength', models.CharField(blank=True, max_length=200, null=True)),
                ('noise_type', models.CharField(blank=True, max_length=200, null=True)),
                ('pleasantness', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='converter.userprofile')),
            ],
            options={
                'verbose_name_plural': 'UserUploadedData',
            },
        ),
    ]
