# Generated by Django 4.1 on 2022-09-19 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('noiselevel', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('timelength', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('noise_type', models.CharField(blank=True, max_length=200, null=True)),
                ('pleasantness', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserUploadedData',
            },
        ),
    ]
