# Generated by Django 4.1 on 2022-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='geom',
            new_name='place',
        ),
        migrations.AddField(
            model_name='geometry',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
