# Generated by Django 4.1 on 2022-09-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_useruploadeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadeddata',
            name='noiselevel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useruploadeddata',
            name='pleasantness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='useruploadeddata',
            name='timelength',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
