# Generated by Django 4.1 on 2022-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_geom_properties_place_geometry_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
