# Generated by Django 4.1 on 2022-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_geometry_type_alter_geometry_geom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='time_ISO8601',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
