# Generated by Django 4.1 on 2022-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_alter_properties_time_epoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='time_epoch',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
